name: Project documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install Doxygen
      run: sudo apt install doxygen -y

    - name: Generate documentation
      run: doxygen Doxyfile