name: Project documentation

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  generate_documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install PHPDocumentor
      run: composer require --dev phpdocumentor/phpdocumentor

    - name: Generate documentation
      run: ./vendor/bin/phpdoc -d src -t docs --encoding=utf-8 --markers=FIXME,TODO --title="Html Object Model" --visibility=public,protected,private --sourcecode